name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node_version: [10]
        os: [ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build --if-present
      - name: npm test
        run: npm run test

        env:
          CI: true
